# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/facultate_an2/SEM2/Arhitectura_calculatoarelor/Laboratoare/proiectMIPS1/proiectMIPS1.cache/wt [current_project]
set_property parent.project_path D:/facultate_an2/SEM2/Arhitectura_calculatoarelor/Laboratoare/proiectMIPS1/proiectMIPS1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/facultate_an2/SEM2/Arhitectura_calculatoarelor/Laboratoare/proiectMIPS1/proiectMIPS1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/facultate_an2/SEM2/Arhitectura_calculatoarelor/Laboratoare/proiectMIPS1/proiectMIPS1.srcs/sources_1/new/Register_File.vhd
  D:/facultate_an2/SEM2/Arhitectura_calculatoarelor/Laboratoare/proiectMIPS1/proiectMIPS1.srcs/sources_1/new/UC.vhd
  D:/facultate_an2/SEM2/Arhitectura_calculatoarelor/Laboratoare/proiectMIPS1/proiectMIPS1.srcs/sources_1/new/InF.vhd
  D:/facultate_an2/SEM2/Arhitectura_calculatoarelor/Laboratoare/proiectMIPS1/proiectMIPS1.srcs/sources_1/new/ID.vhd
  D:/facultate_an2/SEM2/Arhitectura_calculatoarelor/Laboratoare/proiectMIPS1/proiectMIPS1.srcs/sources_1/new/EX.vhd
  D:/facultate_an2/SEM2/Arhitectura_calculatoarelor/Laboratoare/proiectMIPS1/proiectMIPS1.srcs/sources_1/new/Mpg.vhd
  D:/facultate_an2/SEM2/Arhitectura_calculatoarelor/Laboratoare/proiectMIPS1/proiectMIPS1.srcs/sources_1/new/ssd.vhd
  D:/facultate_an2/SEM2/Arhitectura_calculatoarelor/Laboratoare/proiectMIPS1/proiectMIPS1.srcs/sources_1/new/mem.vhd
  D:/facultate_an2/SEM2/Arhitectura_calculatoarelor/Laboratoare/proiectMIPS1/proiectMIPS1.srcs/sources_1/new/test_env.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/facultate_an2/SEM2/Arhitectura_calculatoarelor/Laboratoare/proiectMIPS1/proiectMIPS1.srcs/constrs_1/new/constr.xdc
set_property used_in_implementation false [get_files D:/facultate_an2/SEM2/Arhitectura_calculatoarelor/Laboratoare/proiectMIPS1/proiectMIPS1.srcs/constrs_1/new/constr.xdc]


synth_design -top test_env -part xc7a35tcpg236-1


write_checkpoint -force -noxdef test_env.dcp

catch { report_utilization -file test_env_utilization_synth.rpt -pb test_env_utilization_synth.pb }
